// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from proto

package sinova.tcp.protocol.standard.demo;

import java.util.Objects;

public class ResendInfo {

	Integer sendTimes;
	Long lastSendTime;

	public ResendInfo() {
	}

	public ResendInfo(Integer sendTimes, Long lastSendTime) {
		this.sendTimes = sendTimes;
		this.lastSendTime = lastSendTime;
	}

	public Integer getSendTimes() {

		return sendTimes;
	}

	public void setSendTimes(Integer sendTimes) {
		this.sendTimes = sendTimes;
	}

	public Long getLastSendTime() {

		return lastSendTime;
	}

	public void setLastSendTime(Long lastSendTime) {
		this.lastSendTime = lastSendTime;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null || this.getClass() != obj.getClass()) {
			return false;
		}
		final ResendInfo that = (ResendInfo) obj;
		return Objects.equals(this.sendTimes, that.sendTimes) && Objects.equals(this.lastSendTime, that.lastSendTime);
	}

	@Override
	public int hashCode() {
		return Objects.hash(sendTimes, lastSendTime);
	}

	@Override
	public String toString() {
		return "ResendInfo{" + "sendTimes=" + sendTimes + ", lastSendTime=" + lastSendTime + '}';
	}

}
