// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from proto

package sinova.tcp.protocol.standard.demo;

import io.protostuff.Input;
import io.protostuff.Output;
import io.protostuff.Schema;

import java.io.IOException;

import javax.annotation.Generated;

@Generated("java_bean_model")
public class ResendInfoSchema implements Schema<ResendInfo> {

	static final ResendInfo DEFAULT_INSTANCE = new ResendInfo();
	static final Schema<ResendInfo> SCHEMA = new ResendInfoSchema();

	public static ResendInfo getDefaultInstance() {
		return DEFAULT_INSTANCE;
	}

	public static Schema<ResendInfo> getSchema() {
		return SCHEMA;
	}

	public static final int FIELD_NONE = 0;
	public static final int FIELD_SEND_TIMES = 1;
	public static final int FIELD_LAST_SEND_TIME = 2;

	public ResendInfoSchema() {
	}

	public ResendInfo newMessage() {
		return new ResendInfo();
	}

	public Class<ResendInfo> typeClass() {
		return ResendInfo.class;
	}

	public String messageName() {
		return ResendInfo.class.getSimpleName();
	}

	public String messageFullName() {
		return ResendInfo.class.getName();
	}

	public boolean isInitialized(ResendInfo message) {
		return true;
	}

	public void mergeFrom(Input input, ResendInfo message) throws IOException {
		for (int fieldIx = input.readFieldNumber(this); fieldIx != FIELD_NONE; fieldIx = input.readFieldNumber(this)) {
			mergeFrom(input, message, fieldIx);
		}
	}

	public void mergeFrom(Input input, ResendInfo message, int fieldIx) throws IOException {
		switch (fieldIx) {
		case FIELD_NONE:
			return;
		case FIELD_SEND_TIMES:
			message.sendTimes = input.readInt32();
			break;
		case FIELD_LAST_SEND_TIME:
			message.lastSendTime = input.readInt64();
			break;
		default:
			input.handleUnknownField(fieldIx, this);
		}
	}

	private static int[] FIELDS_TO_WRITE = { FIELD_SEND_TIMES, FIELD_LAST_SEND_TIME };

	public int[] getWriteFields() {
		return FIELDS_TO_WRITE;
	}

	public void writeTo(Output output, ResendInfo message) throws IOException {
		int[] toWrite = getWriteFields();
		for (int i = 0; i < toWrite.length; i++) {
			writeTo(output, message, toWrite[i]);
		}
	}

	public void writeTo(Output output, ResendInfo message, int fieldIx) throws IOException {
		switch (fieldIx) {
		case FIELD_NONE:
			break;
		case FIELD_SEND_TIMES:
			output.writeInt32(FIELD_SEND_TIMES, message.sendTimes, false);
			break;
		case FIELD_LAST_SEND_TIME:
			output.writeInt64(FIELD_LAST_SEND_TIME, message.lastSendTime, false);
			break;
		default:
			break;
		}
	}

	public String getFieldName(int number) {
		return Integer.toString(number);
	}

	public int getFieldNumber(String name) {
		return Integer.parseInt(name);
	}
}
