// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from proto

package sinova.tcp.protocol.standard.demo;

import io.protostuff.Input;
import io.protostuff.Output;
import io.protostuff.Schema;

import java.io.IOException;

import javax.annotation.Generated;

@Generated("java_bean_model")
public class SmsReportRespSchema implements Schema<SmsReportResp> {

	static final SmsReportResp DEFAULT_INSTANCE = new SmsReportResp();
	static final Schema<SmsReportResp> SCHEMA = new SmsReportRespSchema();

	public static SmsReportResp getDefaultInstance() {
		return DEFAULT_INSTANCE;
	}

	public static Schema<SmsReportResp> getSchema() {
		return SCHEMA;
	}

	public static final int FIELD_NONE = 0;
	public static final int FIELD_CLIENT_MT_SEQUENCE = 2;
	public static final int FIELD_SYS_MT_SEQUENCE = 3;

	public SmsReportRespSchema() {
	}

	public SmsReportResp newMessage() {
		return new SmsReportResp();
	}

	public Class<SmsReportResp> typeClass() {
		return SmsReportResp.class;
	}

	public String messageName() {
		return SmsReportResp.class.getSimpleName();
	}

	public String messageFullName() {
		return SmsReportResp.class.getName();
	}

	public boolean isInitialized(SmsReportResp message) {
		return true;
	}

	public void mergeFrom(Input input, SmsReportResp message) throws IOException {
		for (int fieldIx = input.readFieldNumber(this); fieldIx != FIELD_NONE; fieldIx = input.readFieldNumber(this)) {
			mergeFrom(input, message, fieldIx);
		}
	}

	public void mergeFrom(Input input, SmsReportResp message, int fieldIx) throws IOException {
		switch (fieldIx) {
		case FIELD_NONE:
			return;
		case FIELD_CLIENT_MT_SEQUENCE:
			message.clientMtSequence = input.readInt64();
			break;
		case FIELD_SYS_MT_SEQUENCE:
			message.sysMtSequence = input.readInt64();
			break;
		default:
			input.handleUnknownField(fieldIx, this);
		}
	}

	private static int[] FIELDS_TO_WRITE = { FIELD_CLIENT_MT_SEQUENCE, FIELD_SYS_MT_SEQUENCE };

	public int[] getWriteFields() {
		return FIELDS_TO_WRITE;
	}

	public void writeTo(Output output, SmsReportResp message) throws IOException {
		int[] toWrite = getWriteFields();
		for (int i = 0; i < toWrite.length; i++) {
			writeTo(output, message, toWrite[i]);
		}
	}

	public void writeTo(Output output, SmsReportResp message, int fieldIx) throws IOException {
		switch (fieldIx) {
		case FIELD_NONE:
			break;
		case FIELD_CLIENT_MT_SEQUENCE:
			output.writeInt64(FIELD_CLIENT_MT_SEQUENCE, message.clientMtSequence, false);
			break;
		case FIELD_SYS_MT_SEQUENCE:
			output.writeInt64(FIELD_SYS_MT_SEQUENCE, message.sysMtSequence, false);
			break;
		default:
			break;
		}
	}

	public String getFieldName(int number) {
		return Integer.toString(number);
	}

	public int getFieldNumber(String name) {
		return Integer.parseInt(name);
	}
}
