// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from proto

package sinova.tcp.protocol.standard.demo;

import java.util.Objects;

import sinova.tcp.protocol.IReq;

public class SmsReportReq implements IReq {

	ResendInfo resendInfo;
	Integer userId;
	Long clientMtSequence;
	Long sysMtSequence;
	String reportCode;

	public SmsReportReq() {
	}

	public SmsReportReq(Integer userId, Long clientMtSequence, Long sysMtSequence, String reportCode) {
		this.userId = userId;
		this.clientMtSequence = clientMtSequence;
		this.sysMtSequence = sysMtSequence;
		this.reportCode = reportCode;
	}

	public ResendInfo getResendInfo() {
		return resendInfo;
	}

	public void setResendInfo(ResendInfo resendInfo) {
		this.resendInfo = resendInfo;
	}

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public Long getClientMtSequence() {
		return clientMtSequence;
	}

	public void setClientMtSequence(Long clientMtSequence) {
		this.clientMtSequence = clientMtSequence;
	}

	public Long getSysMtSequence() {
		return sysMtSequence;
	}

	public void setSysMtSequence(Long sysMtSequence) {
		this.sysMtSequence = sysMtSequence;
	}

	public String getReportCode() {
		return reportCode;
	}

	public void setReportCode(String reportCode) {
		this.reportCode = reportCode;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null || this.getClass() != obj.getClass()) {
			return false;
		}
		final SmsReportReq that = (SmsReportReq) obj;
		return Objects.equals(this.resendInfo, that.resendInfo) && Objects.equals(this.userId, that.userId)
				&& Objects.equals(this.clientMtSequence, that.clientMtSequence)
				&& Objects.equals(this.sysMtSequence, that.sysMtSequence)
				&& Objects.equals(this.reportCode, that.reportCode);
	}

	@Override
	public int hashCode() {
		return Objects.hash(resendInfo, userId, clientMtSequence, sysMtSequence, reportCode);
	}

	@Override
	public String toString() {
		return "SmsReportReq{" + "resendInfo=" + resendInfo + ", userId=" + userId + ", clientMtSequence="
				+ clientMtSequence + ", sysMtSequence=" + sysMtSequence + ", reportCode=" + reportCode + '}';
	}

}
