// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from proto

package sinova.tcp.protocol.simple;

import io.protostuff.Input;
import io.protostuff.Output;
import io.protostuff.Schema;

import java.io.IOException;

import javax.annotation.Generated;

@Generated("java_bean_model")
public class LoginRespSchema implements Schema<LoginResp> {

	static final LoginResp DEFAULT_INSTANCE = new LoginResp();
	static final Schema<LoginResp> SCHEMA = new LoginRespSchema();

	public static LoginResp getDefaultInstance() {
		return DEFAULT_INSTANCE;
	}

	public static Schema<LoginResp> getSchema() {
		return SCHEMA;
	}

	public static final int FIELD_NONE = 0;
	public static final int FIELD_SUCCESS = 1;
	public static final int FIELD_ERROR_CODE = 2;
	public static final int FIELD_CONNECTION_TYPE = 3;

	public LoginRespSchema() {
	}

	public LoginResp newMessage() {
		return new LoginResp();
	}

	public Class<LoginResp> typeClass() {
		return LoginResp.class;
	}

	public String messageName() {
		return LoginResp.class.getSimpleName();
	}

	public String messageFullName() {
		return LoginResp.class.getName();
	}

	public boolean isInitialized(LoginResp message) {
		return true;
	}

	public void mergeFrom(Input input, LoginResp message) throws IOException {
		for (int fieldIx = input.readFieldNumber(this); fieldIx != FIELD_NONE; fieldIx = input.readFieldNumber(this)) {
			mergeFrom(input, message, fieldIx);
		}
	}

	public void mergeFrom(Input input, LoginResp message, int fieldIx) throws IOException {
		switch (fieldIx) {
		case FIELD_NONE:
			return;
		case FIELD_SUCCESS:
			message.success = input.readBool();
			break;
		case FIELD_ERROR_CODE:
			message.errorCode = input.readString();
			break;
		case FIELD_CONNECTION_TYPE:
			message.connectionType = input.readInt32();
			break;
		default:
			input.handleUnknownField(fieldIx, this);
		}
	}

	private static int[] FIELDS_TO_WRITE = { FIELD_SUCCESS, FIELD_ERROR_CODE, FIELD_CONNECTION_TYPE };

	public int[] getWriteFields() {
		return FIELDS_TO_WRITE;
	}

	public void writeTo(Output output, LoginResp message) throws IOException {
		int[] toWrite = getWriteFields();
		for (int i = 0; i < toWrite.length; i++) {
			writeTo(output, message, toWrite[i]);
		}
	}

	public void writeTo(Output output, LoginResp message, int fieldIx) throws IOException {
		switch (fieldIx) {
		case FIELD_NONE:
			break;
		case FIELD_SUCCESS:
			output.writeBool(FIELD_SUCCESS, message.success, false);
			break;
		case FIELD_ERROR_CODE:
			output.writeString(FIELD_ERROR_CODE, message.errorCode, false);
			break;
		case FIELD_CONNECTION_TYPE:
			output.writeInt32(FIELD_CONNECTION_TYPE, message.connectionType, false);
			break;
		default:
			break;
		}
	}

	public String getFieldName(int number) {
		return Integer.toString(number);
	}

	public int getFieldNumber(String name) {
		return Integer.parseInt(name);
	}
}
