// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from proto

package sinova.tcp.protocol.simple;

import java.util.Objects;

import sinova.tcp.protocol.ILoginResp;

public class LoginResp implements ILoginResp {

	Boolean success;
	String errorCode;
	Integer connectionType;

	public LoginResp() {
	}

	public LoginResp(Boolean success, String errorCode, Integer connectionType) {
		this.success = success;
		this.errorCode = errorCode;
		this.connectionType = connectionType;
	}

	public Boolean getSuccess() {

		return success;
	}

	public void setSuccess(Boolean success) {
		this.success = success;
	}

	public String getErrorCode() {

		return errorCode;
	}

	public void setErrorCode(String errorCode) {
		this.errorCode = errorCode;
	}

	public Integer getConnectionType() {

		return connectionType;
	}

	public void setConnectionType(Integer connectionType) {
		this.connectionType = connectionType;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null || this.getClass() != obj.getClass()) {
			return false;
		}
		final LoginResp that = (LoginResp) obj;
		return Objects.equals(this.success, that.success) && Objects.equals(this.errorCode, that.errorCode)
				&& Objects.equals(this.connectionType, that.connectionType);
	}

	@Override
	public int hashCode() {
		return Objects.hash(success, errorCode, connectionType);
	}

	@Override
	public String toString() {
		return "LoginResp{" + "success=" + success + ", errorCode=" + errorCode + ", connectionType=" + connectionType
				+ '}';
	}

}
