// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from proto

package sinova.tcp.protocol.simple;

import java.util.Objects;

import sinova.tcp.protocol.ILoginReq;

public class LoginReq implements ILoginReq {

	Integer userId;
	String appName;
	String authOrigin;
	Long timestamp;

	public LoginReq() {
	}

	public LoginReq(Integer userId, String appName, String authOrigin, Long timestamp) {
		this.userId = userId;
		this.appName = appName;
		this.authOrigin = authOrigin;
		this.timestamp = timestamp;
	}

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getAppName() {
		return appName;
	}

	public void setAppName(String appName) {
		this.appName = appName;
	}

	public String getAuthOrigin() {
		return authOrigin;
	}

	public void setAuthOrigin(String authOrigin) {
		this.authOrigin = authOrigin;
	}

	public Long getTimestamp() {

		return timestamp;
	}

	public void setTimestamp(Long timestamp) {
		this.timestamp = timestamp;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null || this.getClass() != obj.getClass()) {
			return false;
		}
		final LoginReq that = (LoginReq) obj;
		return Objects.equals(this.userId, that.userId) && Objects.equals(this.appName, that.appName)
				&& Objects.equals(this.authOrigin, that.authOrigin) && Objects.equals(this.timestamp, that.timestamp);
	}

	@Override
	public int hashCode() {
		return Objects.hash(userId, appName, authOrigin, timestamp);
	}

	@Override
	public String toString() {
		return "LoginReq{" + "userId=" + userId + ", appName=" + appName + ", authOrigin=" + authOrigin
				+ ", timestamp=" + timestamp + '}';
	}
}
