// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from proto

package sinova.tcp.protocol.simple;

import io.protostuff.Input;
import io.protostuff.Output;
import io.protostuff.Schema;

import java.io.IOException;

import javax.annotation.Generated;

@Generated("java_bean_model")
public class LogoutReqSchema implements Schema<LogoutReq> {

	static final LogoutReq DEFAULT_INSTANCE = new LogoutReq();
	static final Schema<LogoutReq> SCHEMA = new LogoutReqSchema();

	public static LogoutReq getDefaultInstance() {
		return DEFAULT_INSTANCE;
	}

	public static Schema<LogoutReq> getSchema() {
		return SCHEMA;
	}

	public static final int FIELD_NONE = 0;

	public LogoutReqSchema() {
	}

	public LogoutReq newMessage() {
		return new LogoutReq();
	}

	public Class<LogoutReq> typeClass() {
		return LogoutReq.class;
	}

	public String messageName() {
		return LogoutReq.class.getSimpleName();
	}

	public String messageFullName() {
		return LogoutReq.class.getName();
	}

	public boolean isInitialized(LogoutReq message) {
		return true;
	}

	public void mergeFrom(Input input, LogoutReq message) throws IOException {
		for (int fieldIx = input.readFieldNumber(this); fieldIx != FIELD_NONE; fieldIx = input.readFieldNumber(this)) {
			mergeFrom(input, message, fieldIx);
		}
	}

	public void mergeFrom(Input input, LogoutReq message, int fieldIx) throws IOException {
		switch (fieldIx) {
		case FIELD_NONE:
			return;
		default:
			input.handleUnknownField(fieldIx, this);
		}
	}

	private static int[] FIELDS_TO_WRITE = {};

	public int[] getWriteFields() {
		return FIELDS_TO_WRITE;
	}

	public void writeTo(Output output, LogoutReq message) throws IOException {
		int[] toWrite = getWriteFields();
		for (int i = 0; i < toWrite.length; i++) {
			writeTo(output, message, toWrite[i]);
		}
	}

	public void writeTo(Output output, LogoutReq message, int fieldIx) throws IOException {
		switch (fieldIx) {
		case FIELD_NONE:
			break;
		default:
			break;
		}
	}

	public String getFieldName(int number) {
		return Integer.toString(number);
	}

	public int getFieldNumber(String name) {
		return Integer.parseInt(name);
	}
}
