// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from proto

package sinova.tcp.protocol.simple;

import io.protostuff.Input;
import io.protostuff.Output;
import io.protostuff.Schema;

import java.io.IOException;

import javax.annotation.Generated;

@Generated("java_bean_model")
public class PingRespSchema implements Schema<PingResp> {

	static final PingResp DEFAULT_INSTANCE = new PingResp();
	static final Schema<PingResp> SCHEMA = new PingRespSchema();

	public static PingResp getDefaultInstance() {
		return DEFAULT_INSTANCE;
	}

	public static Schema<PingResp> getSchema() {
		return SCHEMA;
	}

	public static final int FIELD_NONE = 0;

	public PingRespSchema() {
	}

	public PingResp newMessage() {
		return new PingResp();
	}

	public Class<PingResp> typeClass() {
		return PingResp.class;
	}

	public String messageName() {
		return PingResp.class.getSimpleName();
	}

	public String messageFullName() {
		return PingResp.class.getName();
	}

	public boolean isInitialized(PingResp message) {
		return true;
	}

	public void mergeFrom(Input input, PingResp message) throws IOException {
		for (int fieldIx = input.readFieldNumber(this); fieldIx != FIELD_NONE; fieldIx = input.readFieldNumber(this)) {
			mergeFrom(input, message, fieldIx);
		}
	}

	public void mergeFrom(Input input, PingResp message, int fieldIx) throws IOException {
		switch (fieldIx) {
		case FIELD_NONE:
			return;
		default:
			input.handleUnknownField(fieldIx, this);
		}
	}

	private static int[] FIELDS_TO_WRITE = {};

	public int[] getWriteFields() {
		return FIELDS_TO_WRITE;
	}

	public void writeTo(Output output, PingResp message) throws IOException {
		int[] toWrite = getWriteFields();
		for (int i = 0; i < toWrite.length; i++) {
			writeTo(output, message, toWrite[i]);
		}
	}

	public void writeTo(Output output, PingResp message, int fieldIx) throws IOException {
		switch (fieldIx) {
		case FIELD_NONE:
			break;
		default:
			break;
		}
	}

	public String getFieldName(int number) {
		return Integer.toString(number);
	}

	public int getFieldNumber(String name) {
		return Integer.parseInt(name);
	}
}
